apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-go
  namespace: default
spec:
  dnsNames:
    - devilyn.ml
  secretName: letsencrypt
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

